// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductWebApplication.Data;

namespace ProductWebApplication.Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20190727115818_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductWebApplication.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1fc43ab-c2a9-4e98-8ff0-0953740e1bee"),
                            Name = "Zszywacz biurowy",
                            Price = 35.15m
                        },
                        new
                        {
                            Id = new Guid("bd33dd6d-2ec6-4824-b8f3-3f1395ba51df"),
                            Name = "Gumka do mazania",
                            Price = 3.06m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
